coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unit
        branches: 
          - master
        if_ci_failed: error
        only_pulls: false
  tests:
    paths:
      - test/