dispatcherConverter:
    # Absolute path to the src folder of the dispatcher sdk
    sdkSrc:
    onPremise:
        # Absolute path to the dispatcher.any file
        dispatcherAnySrc:
        httpdSrc:
        vhostsToConvert:
        variablesToReplace:
            TIER: "ENVIRONMENT_TYPE"
            HOSTADDRESS: "hostAddress"
            HOSTNAME: "hostName"
            WWW_SSL_HOSTADDRESS: "www_ssl_hostAddress"
        appendToVhosts:
        pathToPrepend:
        portsToMap:
    ams:
        # Absolute path to dispatcher config folder
        cfg:
repositoryModernizer:
    # groupId to be used for newly created packages
    groupId:
    # information about parent pom
    parentPom:
        # absolute path to the parent pom file
        path:
        # the artifactId to be set for the parent pom
        artifactId:
        # the application title to be set for the parent pom
        appTitle:
    # information required for all package
    all:
        # prefix that is to be used to set the artifactId for all package
        artifactId:
        # application title
        appTitle:
    # information about projects
    projects:
        - # absolute path to the project folder
          projectPath:
          # relative path(s) (w.r.t. the project folder) to the existing content package(s) that needs to be restructured
          # (expects one or more relative paths to be provided in array format)
          existingContentPackageFolder:
              -
          # relative path (w.r.t. the existing content package folder) to the filter.xml file
          # (If not specified, default path `/src/main/content/META-INF/vault/filter.xml` will be used.)
          relativePathToExistingFilterXml:
          # relative path (w.r.t. the existing content package folder) to the jcr_root directory
          # (If not specified, default path `/src/main/content/jcr_root` will be used)
          relativePathToExistingJcrRoot:
          # prefix that is to be used to set the artifactId for newly created ui.apps and ui.content packages
          artifactId:
          # application title
          appTitle:
indexConverter:
    # Path to the jcr_root directory of the package containing the Ensure Index Definitions
    # (please ignore if there are no Ensure Index Definitions)
    # eg. /Users/xyz/sampleCode/content/src/main/content/jcr_root
    ensureIndexDefinitionContentPackageJcrRootPath:
    # Path to the jcr_root directory of the package containing the Ensure Oak Index OSGI Configuration
    # (please ignore if there are no Ensure Index Definitions)
    # eg. /Users/xyz/sampleCode/CONFIG/src/main/content/jcr_root
    ensureIndexDefinitionConfigPackageJcrRootPath:
    # Version of AEM customer is on, used to determine the baseline index definitions
    aemVersion:
    # Path to the customer OAK Index Definition directory
    # (please ignore if there are no Oak Index Definitions)
    # eg /Users/xyz/sampleCode/ui.apps/src/main/content/jcr_root/_oak_index
    customOakIndexDirectoryPath:
    # Path to the existing package `filter.xml` file
    # eg /Users/xyz/sampleCode/ui.apps/src/main/content/META-INF/vault/filter.xml
    filterXMLPath:
