name: Workflow for Codecov Action
on: [push, pull_request]

jobs:

  codecoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Execute Tests
        run: npm test
        
      - name: upload code coverage
        run: bash <(curl -s https://codecov.io/bash)